zenphoto/zenphoto

zp-core/404.php
If a requested image is not found in the cache, there appears to be code in place to try and generate the image on the fly.
However, this code is broken, as the name of the image file is not included in the call to getImageProcessorURIFromCacheName() (only the path to the image is included).
Adding:
'/'.$image
to the end of the path seems to work.
I haven't been able to determine if there are any limits to stop a user filling up all the space on the server by repeatedly requesting images at 1-pixel increments (which wouldn't be a problem without this fix, as it would just give an error).
=> Fix automatic cache rebuild

zp-core/template-functions.php
The admin menu in version 1.4.7 generates invalid HTML, which breaks some themes. Ensure that all div elements are closed.
=> Fix issue 906 - unclosed <div>

zp-core/admin-functions.php, zp-core/admin-options.php, zp-core/template-functions.php, zp-core/zp-extensions/favoritesHandler/favoritesClass.php, zp-core/zp-extensions/tag_suggest/tag.css
On a fresh install of the latest master I noticed that tag suggestions were appearing to the right of input boxes instead of underneath, which also meant two clicks were needed - the first one moved the box to under the input box (weird behavior). This fixes both issues.
=> Fixed the position of tag suggestions

zp-core/functions.php
getNotViewableImages uses a wrong clause when determining which images
should be hidden. It checks for show = 0 and albumid = #. This doesn't
exclude the images which have show =1 but are contained in albums the
user doesn't have access to. This makes the printAllTagsAs(with
checkAccess = true) print the wrong count as it will count all items
with the tag but not exclude the items the user doesn't have access to.
The query is trying to come up with a list of images that need to be hidden. Fix is to exclude items marked show = 0 and also the ones that are present in albums the user doesn't have access to.
=> getNotViewableImages uses a wrong clause when determining which images should be hidden

zp-core/functions.php
The method returns an array, it shouldn't be printing html content.
=> getAllTagsCount called with checkaccess = true prints debug spew

zp-core/locale/de_DE/LC_MESSAGES/zenphoto.po
It took me some time to understand the german message since it's inconsistent with the wording of the rest of the UI.
=> Changed misleading/inconsistent translation. +typos

zp-core/utilities/gallery_statistics.php
'Gallery Statistics' page has many tables of data, among them:
- images ordered by most viewed
- albums ordered by most viewed
This adds a new 'most viewed images' table for albums.
Count displayed against each album is the average hitcounter value for all images in the album.
=> Addition to Gallery Statistics - new 'most viewed image' table for albums

zp-core/setup/setup-option-defaults.php
rel attribute is used by tinyMCE, but not allowed by default by zenphoto so it is filtered.
also fix typo and an older discus about frameborder attribute on iframe (not supported by html5 as marginwidth, marginheight and scrolling attributes
(https://github.com/zenphoto/zenphoto/commit/96b8beae38bb34e3275ed888b41b4c1463d54b3a)
=> fix rel attribute on <a> tag

zp-core/exif/exif.php
Calculating 35mmEquivFocalLength more accurately, especially for smaller focal lengths (like mobile phones or action cams)
=> Fix for locale-unaware floatval()

zp-core/utilities/list_locales.php
leading to a `?>` displayed at the end of `list_locales.php` page.
=> removed orphan closing php tag

zp-core/template-functions.php
This feature was present a long time ago, before some major changes to dynamic albums. I would really like to have it back.
We can edit images from admin toolbox even in search context, so why not while browsing a dynamic album?
I have kept disabled the "delete" button though, because that is actually useless and might be confusing,  since deleting the image from the corresponding static album and from the file system too.
I've tested this change and I can't see any contraindication at the moment, but I might be missing something, so any comment or review is very welcome.
=> Restore edit button in admintoolbox for images of dynamic albums

zp-core/template-functions.php
Since there was not $image defined nor any $_zp_current_image, getSizeCustomImage(), if called from printCustomAlbumThumbImage(), always returned "false", leading to missing width and heigth for
album thumbs. 
Keep in mind that some changes are probably needed in themes too, because the variable $size passed to the function, at least by the zenpage theme, is "NULL" at the moment, as you can see here for zenpage/gallery.php:
https://github.com/zenphoto/zenphoto/blob/b24da2fd019194bbc63ac5c3584d95246e4d573a/themes/zenpage/gallery.php#L46
Same thing for album.php and search.php...
In my theme I've tested the value 95, but it also seems to work properly using either false or an empty string.
I'm not sure I'm proposing the best solution for this issue, or if I'm missing some contraindication, …
=> Fix missing width and height in album thumbs

zp-core/functions-basic.php
When we setup zenphoto behind a reverse proxy such as nginx or haproxy, the server thinks it is receiving an http request while the client has submitted an https request....resulting in an infinite redirection loop.
In that case, the reverse proxy can add a "Forwarded" or "X-Forwarded-Proto" header to inform the backend about the real protocol used by the client. (see https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/ )
=> secureServer function: consider https requests behind reverse proxies

themes/zenpage/functions.php
Working on a new theme using some zenpage theme's functions, I found a little bug that leads to an empty link to the first page of news if the option `zenpage_zp_index_news` is active.
It seems to me that the changes in this commit fix the problem, I'm not sure if there are some contraindications though. 
PS
I hope to be able to release and share my new theme as soon as possible.
=> Fix empty link for newsOnIndex

zp-core/zp-extensions/cookieconsent.php
It seems to me that **compliances** is intended instead. Please discard this pull request if I'm wrong.
=> Is really "complicances" the intended word?

zp-core/template-functions.php
With **search_within** option set to false, title was still outputted as **_Search within previous results_** in PHP, though it was corrected in JavaScript after clicking on radio buttons.
So the variable **$hint** has to be corrected for PHP, taking into account the **search_within** option, while has to be left unchanged for JavaScript, but then with a different name. I used **$hintJS** for that.
Possibly there is a cleaner way to fix this. If so, please change or replace this pull request.
=> Fix title for search submit button

zp-core/class-feed.php, zp-core/zp-extensions/rss.php, zp-core/zp-extensions/zenpage/zenpage-template-functions.php
1. printAllNewsCategories is not showing subcategories in list mode, which should be the expected context sensitive behavior.
While it's possible to bypass this function, using directly printNestedMenu with the proper parameters (I'm going to do so in my themes from now on), it's probably also possible to easily fix this, if there are not unwanted consequences somewhere else that I'm not aware of.
2. Having played a bit with RSS feeds in the past few days, I noticed the possibility to create a feed for latest news from a single category. Probably nobody is using it anymore, but the title of that feed is missing a separator between gallery title and category title. Hopefully this trivial fix can solve the problem, unless there is a better way.
3. Links from comments feed to a real comment …
=> Three proposed small fixes for news category menu, news category feed and comments feed

zp-core/admin-plugins.php
Working on a new plugin, I discovered that the author site link was not printed in admin panel. This should fix the issue.
=> Fix for not printed plugin site link

zp-core/admin-functions.php, zp-core/zp-extensions/cacheManager.php, zp-core/zp-extensions/cacheManager/cacheImages.php
And remove the button for cache cleaning from the same page
=> Allow caching images assigned to a dynamic album from its admin-edit page

zp-core/zp-extensions/image_album_statistics.php
Fix a return type in phpdoc.  
The function `getImageStatistic()` should be returning `array` type.
=> Fix return type in phpdoc 

zp-core/setup/index.php
This is a problem that continues to happen to me and others sometimes. There are other mentions of it on here and the zenphoto forum, including from me in 2014 (and it happened to me twice this year)
e.g.
https://forum.zenphoto.org/discussion/906506/options-table-spam
https://forum.zenphoto.org/discussion/1410812/millions-of-records-in-the-options-table-duplicate-options-continuously-created
https://github.com/zenphoto/zenphoto/issues/532
I finally looked into the code and I believe I have found the cause of it - if the database update script is run while users are still browsing the website, there could be a race-condition:
1) Drop the constraint (line 2333)
2) A duplicate entry is added to the table
3) Try to add the constraint (line 2334) but it fails because of the duplicate
Here, the …
=> Fix unique_option constraint being removed

zp-core/class-gallery.php
Not pushing it myself because this is is a new function I wasn't aware of, so I need some supervision here. It was not easy to spot this, I finally echoed get_class($obj) in search results page and I got the missing uppercase!
=> Typo preventing sharing thumbs on the last album page in search results

zp-core/admin-options.php
thumb_transition was not disabled at all, while thumb_transition_min and thumb_transition_max were simply removed from the theme option page if disabled.
=> Proper disable attribute for the new thumb_transition options

zp-core/zp-extensions/related_items.php
If an element has a multiple words tag, getRelatedItems('all') returns an empty array. Since multiple words tags are allowed by zenphoto, returning proper search results, I guess they should work also for related items searches. This is a possible fix, tested and working, but could there be a better solution?
=> Related items for tags with blank chars

zp-core/template-functions.php
To allow standard thumbs display for password protected albums if an user has gained rights on them by inserting the password
=> Disclose album thumb if password has been provided

zp-core/class-gallery.php
getOption() there doesn't work because it is stored in the gallery object option.
=> Fix missing custom copyright site url

zp-core/template-functions.php, zp-core/zp-extensions/downloadList.php
- Fix broken printDownloadURL for full image
- Fix check for album existence
- Added a new 404 message for broken downloads
- Set a very fast expiring cookie after list generation for album.zip
- Todo eventually: merge the old (and still used) internal 404/403 message with the new one
=> Proper password page for downloadList

zp-core/zp-extensions/zenpage/class-zenpage.php
This method was ignoring the $number parameter and returning always all of the pages.
=> Fix for number of pages returned by getPages()

zp-core/zp-extensions/featured_image.php
Fixes for 
```
ERROR: Call to undefined method ZenpagePage::getFeaturedImage() in /......./zp-core/zp-extensions/featured_image.php on line 713
ERROR: Call to undefined method ZenpageNews::getFeaturedImage() in /......./zp-core/zp-extensions/featured_image.php on line 713
```
when using printFeaturedImageThumb in theme template.
=> Fix for featured_image printFeaturedImageThumb not working

zp-core/classes/class-authority.php
Passwords are never marked as matching since the check is done when the confirmation field is hidden
=> Fix password match in registration form

zp-core/template-functions.php, zp-core/zp-extensions/favoritesHandler.php, zp-core/zp-extensions/favoritesHandler/class-favorites.php
As discussed here #1421
- Avoid duplicate instances of the same image/album
- Fix Users watching list in admin page
- Conform case letters of new instances to possibly existing ones, since instance options are case-insensitive
- Prevent tag_suggest bind code from output when not needed (i.e. most of the times)
- Fix page count and a wrong use of $this in the static function pageCount()
- Add instance name set to head title and use the text from the relevant option
=> Fixes for favoritesHandler extension

zp-core/classes/class-themeobject.php, zp-core/zp-extensions/comment_form.php, zp-core/zp-extensions/comment_form/comment_form.php, zp-core/zp-extensions/comment_form/functions.php, zp-core/zp-extensions/contact_form.php
The error message part has to be discussed.
One more thing to clarify is that, since no verification on quiz fields is done for logged users with post comments rights, we should either:
1. Remove the required attribute for logged users
2. Remove the input fields from the form for logged users
3. Perform the verification, no matter what
We could also add, like for the Capcha field, a "For guests" option to quiz fields,
=> Fixes for comment form quiz fields

zp-core/zp-extensions/openstreetmap.php, zp-core/zp-extensions/openstreetmap/leaflet.css, zp-core/zp-extensions/openstreetmap/openstreetmap.css
- Added missing `title` attributes to Image page links for markers on the map (title & thumb)
- Added classes for styling of title and thumbs for markers on the map (`openstreetmap-thumb`, `openstreetmap-title`)
- Added missing `alt` attribute to thumbs for markers on the map
- Removed trailing `<br>` after titles in thumbs (unnecessary, if need be - styling can be done with CSS now)
- Added option to specify `length` of title displayed for markers on the map.
- Added option to specify `length` of descriptions displayed for markers on the map.
- Added option to choose Default thumb or a Custom sized image to be displayed in markers on the map.
- Added option to specify the `width` of custom image, used as thumb.
- Changed default Custom image `width` to **120px** (to remove resizing of …
=> openstreetmap: markers styling and new options

zp-core/zp-extensions/openstreetmap.php, zp-core/zp-extensions/openstreetmap/leaflet-providers.js
Hey zenphoto dev team!
I highly appreciate your CMS since many years to publish my own little website!
To display my photos on the map I am using HERE map services. Unfortunately this has stopped working recently. The background is that HERE will remove its deprecated maptile service v2 very soon. This is replaced with HERE Raster tile api v3.
I created a fork with a modified osm plugin which includes the changes necessary to migrate to the new HERE raster tile api. This also switches from app-id and app-code to apikey.
I would highly appreciate if this change can be included in one of th upcoming official zenphoto releases! THX!
A few more background on HERE's apis:
Apikeys can be created for free at https://platform.here.com/portal/
Subscription remains for free, pricing details can be …
=> Replace deprecated HERE Map tile v2 with HERE raster tile service v3
